-- Atelier Binding

select CLASSICMODELS.ORDERDETAILS.ORDERNUMBER,CLASSICMODELS.ORDERDETAILS.PRODUCTCODE,CLASSICMODELS.ORDERDETAILS.QUANTITYORDERED,CLASSICMODELS.ORDERDETAILS.PRICEEACH,CLASSICMODELS.ORDERDETAILS.ORDERLINENUMBER,
CLASSICMODELS.PRODUCTS.PRODUCTNAME,CLASSICMODELS.PRODUCTS.PRODUCTLINE
from CLASSICMODELS.ORDERDETAILS,CLASSICMODELS.PRODUCTS
where CLASSICMODELS.PRODUCTS.PRODUCTCODE=CLASSICMODELS.ORDERDETAILS.PRODUCTCODE 
and CLASSICMODELS.PRODUCTS.PRODUCTLINE like 'Vintage%'
order by CLASSICMODELS.ORDERDETAILS.ORDERNUMBER


-- Formatage
DataSet Client
select CLASSICMODELS.CUSTOMERS.CONTACTFIRSTNAME, CLASSICMODELS.CUSTOMERS.CONTACTLASTNAME,CLASSICMODELS.CUSTOMERS.CUSTOMERNAME,
CLASSICMODELS.CUSTOMERS.ADDRESSLINE1, CLASSICMODELS.CUSTOMERS.ADDRESSLINE2, CLASSICMODELS.CUSTOMERS.CITY,
CLASSICMODELS.CUSTOMERS.STATE,CLASSICMODELS.CUSTOMERS.POSTALCODE,CLASSICMODELS.CUSTOMERS.COUNTRY,
CLASSICMODELS.ORDERS.ORDERDATE,CLASSICMODELS.ORDERS.REQUIREDDATE,CLASSICMODELS.ORDERS.SHIPPEDDATE
from CLASSICMODELS.ORDERS, CLASSICMODELS.CUSTOMERS
where CLASSICMODELS.ORDERS.CUSTOMERNUMBER = CLASSICMODELS.CUSTOMERS.CUSTOMERNUMBER
and CLASSICMODELS.ORDERS.ORDERNUMBER=10100

DataSet OrderDetail
select CLASSICMODELS.ORDERDETAILS.ORDERNUMBER, CLASSICMODELS.ORDERDETAILS.QUANTITYORDERED, CLASSICMODELS.ORDERDETAILS.PRICEEACH, CLASSICMODELS.ORDERDETAILS.ORDERLINENUMBER,
CLASSICMODELS.PRODUCTS.PRODUCTNAME, CLASSICMODELS.PRODUCTS.PRODUCTLINE
from CLASSICMODELS.ORDERDETAILS, CLASSICMODELS.PRODUCTS
where CLASSICMODELS.ORDERDETAILS.PRODUCTCODE = CLASSICMODELS.PRODUCTS.PRODUCTCODE
and CLASSICMODELS.ORDERDETAILS.ORDERNUMBER = 10100
order by CLASSICMODELS.ORDERDETAILS.ORDERLINENUMBER

-- Page maître
DataSet Order
select CLASSICMODELS.ORDERDETAILS.ORDERNUMBER,CLASSICMODELS.ORDERDETAILS.PRODUCTCODE,CLASSICMODELS.ORDERDETAILS.QUANTITYORDERED,CLASSICMODELS.ORDERDETAILS.PRICEEACH,CLASSICMODELS.ORDERDETAILS.ORDERLINENUMBER,
CLASSICMODELS.PRODUCTS.PRODUCTNAME,CLASSICMODELS.PRODUCTS.PRODUCTLINE
from CLASSICMODELS.ORDERDETAILS,CLASSICMODELS.PRODUCTS
where CLASSICMODELS.PRODUCTS.PRODUCTCODE=CLASSICMODELS.ORDERDETAILS.PRODUCTCODE 
and CLASSICMODELS.PRODUCTS.PRODUCTLINE like 'Vintage%'
order by CLASSICMODELS.ORDERDETAILS.ORDERNUMBER

-- Groupes
DataSet Orders
select CLASSICMODELS.ORDERDETAILS.ORDERNUMBER,CLASSICMODELS.ORDERDETAILS.PRODUCTCODE,CLASSICMODELS.ORDERDETAILS.QUANTITYORDERED,CLASSICMODELS.ORDERDETAILS.PRICEEACH,CLASSICMODELS.ORDERDETAILS.ORDERLINENUMBER,
CLASSICMODELS.PRODUCTS.PRODUCTNAME,CLASSICMODELS.PRODUCTS.PRODUCTLINE,
CLASSICMODELS.CUSTOMERS.CUSTOMERNAME, CLASSICMODELS.CUSTOMERS.CUSTOMERNUMBER,
CLASSICMODELS.ORDERS.SHIPPEDDATE
from CLASSICMODELS.ORDERDETAILS,CLASSICMODELS.PRODUCTS, CLASSICMODELS.ORDERS, 
CLASSICMODELS.CUSTOMERS
where CLASSICMODELS.PRODUCTS.PRODUCTCODE=CLASSICMODELS.ORDERDETAILS.PRODUCTCODE 
and CLASSICMODELS.CUSTOMERS.CUSTOMERNUMBER=CLASSICMODELS.ORDERS.CUSTOMERNUMBER
and CLASSICMODELS.ORDERS.ORDERNUMBER = CLASSICMODELS.ORDERDETAILS.ORDERNUMBER
and CLASSICMODELS.ORDERDETAILS.ORDERNUMBER is not null
order by CLASSICMODELS.CUSTOMERS.CUSTOMERNAME, CLASSICMODELS.ORDERS.ORDERNUMBER, CLASSICMODELS.ORDERDETAILS.ORDERLINENUMBER

-- Paramètres
CountryCity
select CLASSICMODELS.CUSTOMERS.CITY,CLASSICMODELS.CUSTOMERS.COUNTRY
from CLASSICMODELS.CUSTOMERS
order by CLASSICMODELS.CUSTOMERS.COUNTRY, CLASSICMODELS.CUSTOMERS.CITY

Orders
select CLASSICMODELS.ORDERDETAILS.ORDERNUMBER,CLASSICMODELS.ORDERDETAILS.PRODUCTCODE,CLASSICMODELS.ORDERDETAILS.QUANTITYORDERED,CLASSICMODELS.ORDERDETAILS.PRICEEACH,CLASSICMODELS.ORDERDETAILS.ORDERLINENUMBER,
CLASSICMODELS.PRODUCTS.PRODUCTNAME,CLASSICMODELS.PRODUCTS.PRODUCTLINE,
CLASSICMODELS.CUSTOMERS.CUSTOMERNAME, CLASSICMODELS.CUSTOMERS.CUSTOMERNUMBER,
CLASSICMODELS.ORDERS.SHIPPEDDATE
from CLASSICMODELS.ORDERDETAILS,CLASSICMODELS.PRODUCTS, CLASSICMODELS.ORDERS, 
CLASSICMODELS.CUSTOMERS
where CLASSICMODELS.PRODUCTS.PRODUCTCODE=CLASSICMODELS.ORDERDETAILS.PRODUCTCODE 
and CLASSICMODELS.CUSTOMERS.CUSTOMERNUMBER=CLASSICMODELS.ORDERS.CUSTOMERNUMBER
and CLASSICMODELS.ORDERS.ORDERNUMBER = CLASSICMODELS.ORDERDETAILS.ORDERNUMBER
and CLASSICMODELS.ORDERS.ORDERDATE >= ?
and CLASSICMODELS.ORDERS.ORDERDATE <= ?
and CLASSICMODELS.CUSTOMERS.COUNTRY = ?
and CLASSICMODELS.CUSTOMERS.CITY = ?
order by CLASSICMODELS.CUSTOMERS.CUSTOMERNAME, CLASSICMODELS.ORDERS.ORDERNUMBER, CLASSICMODELS.ORDERDETAILS.ORDERLINENUMBER

-- Graphiques
OrdersByProductLine
select CLASSICMODELS.PRODUCTS.PRODUCTLINE, sum(CLASSICMODELS.ORDERDETAILS.QUANTITYORDERED)
from CLASSICMODELS.ORDERDETAILS, CLASSICMODELS.PRODUCTS
where CLASSICMODELS.ORDERDETAILS.PRODUCTCODE=CLASSICMODELS.PRODUCTS.PRODUCTCODE
GROUP BY CLASSICMODELS.PRODUCTS.PRODUCTLINE
ORDER BY CLASSICMODELS.PRODUCTS.PRODUCTLINE

CommandesGroupéesParVillePays (Graphique Meter) 
select CLASSICMODELS.CUSTOMERS.COUNTRY, CLASSICMODELS.CUSTOMERS.CITY, CLASSICMODELS.ORDERDETAILS.QUANTITYORDERED, CLASSICMODELS.ORDERDETAILS.PRICEEACH
from CLASSICMODELS.ORDERDETAILS, CLASSICMODELS.ORDERS, CLASSICMODELS.CUSTOMERS
where CLASSICMODELS.ORDERDETAILS.ORDERNUMBER=CLASSICMODELS.ORDERS.ORDERNUMBER
and CLASSICMODELS.ORDERS.CUSTOMERNUMBER=CLASSICMODELS.CUSTOMERS.CUSTOMERNUMBER
ORDER BY CLASSICMODELS.CUSTOMERS.COUNTRY, CLASSICMODELS.CUSTOMERS.CITY

-- Crosstab
VenteUSA
select CLASSICMODELS.CUSTOMERS.COUNTRY,CLASSICMODELS.CUSTOMERS.CITY,CLASSICMODELS.ORDERDETAILS.QUANTITYORDERED,CLASSICMODELS.ORDERDETAILS.PRICEEACH,CLASSICMODELS.PRODUCTS.PRODUCTLINE
from CLASSICMODELS.PRODUCTS,CLASSICMODELS.ORDERDETAILS,CLASSICMODELS.ORDERS,CLASSICMODELS.CUSTOMERS
where CLASSICMODELS.CUSTOMERS.CUSTOMERNUMBER=CLASSICMODELS.ORDERS.CUSTOMERNUMBER
and CLASSICMODELS.ORDERS.ORDERNUMBER=CLASSICMODELS.ORDERDETAILS.ORDERNUMBER
and CLASSICMODELS.ORDERDETAILS.PRODUCTCODE=CLASSICMODELS.PRODUCTS.PRODUCTCODE

